// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrfkefjAaJtMoIIBP_eVoZBB7mz7vKSqE',
    appId: '1:325236805162:web:ea24342c0fc10665937d53',
    messagingSenderId: '325236805162',
    projectId: 'jan-sarthi-2f13c',
    authDomain: 'jan-sarthi-2f13c.firebaseapp.com',
    storageBucket: 'jan-sarthi-2f13c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNw4X_tSaxsAHZ_EpaPGMVC24DsdnfmF8',
    appId: '1:325236805162:android:0f3ae17eb8738c24937d53',
    messagingSenderId: '325236805162',
    projectId: 'jan-sarthi-2f13c',
    storageBucket: 'jan-sarthi-2f13c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZoe0PlLAl8PqTXXWS0qsgph0wykUS2A',
    appId: '1:325236805162:ios:a34b933ed6b92167937d53',
    messagingSenderId: '325236805162',
    projectId: 'jan-sarthi-2f13c',
    storageBucket: 'jan-sarthi-2f13c.firebasestorage.app',
    iosBundleId: 'com.example.janSarthi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZoe0PlLAl8PqTXXWS0qsgph0wykUS2A',
    appId: '1:325236805162:ios:a34b933ed6b92167937d53',
    messagingSenderId: '325236805162',
    projectId: 'jan-sarthi-2f13c',
    storageBucket: 'jan-sarthi-2f13c.firebasestorage.app',
    iosBundleId: 'com.example.janSarthi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrfkefjAaJtMoIIBP_eVoZBB7mz7vKSqE',
    appId: '1:325236805162:web:f6689970d9ff96be937d53',
    messagingSenderId: '325236805162',
    projectId: 'jan-sarthi-2f13c',
    authDomain: 'jan-sarthi-2f13c.firebaseapp.com',
    storageBucket: 'jan-sarthi-2f13c.firebasestorage.app',
  );
}
